### ISSUE TITLE
Removing a node from categories doesn't work

### ISSUE THREAD

**Issue by MattIPv4** [do-community/diagram-tool#23]
The option to remove a node from categories (shown top right when a node is selected) doesn't seem to work. Pressing it doesn't appear to remove a node.

This should be fixed so that pressing the option removes the node from categories -- this should be shown visually with the node no longer being in a category and also with the option disappearing from the menu when the node is in no categories.

Whilst we're fixing this, we should also update the copy used from `Remove all categories` to `Remove from all categories`.

**Comment by JakeMakesStuff** [comment]
Reopening since although the functionality works it doesn't save.
