### ISSUE TITLE
Using arrows to move nodes should snap to grid

### ISSUE THREAD

**Issue by MattIPv4** [do-community/diagram-tool#25]
Now that we have removed the grid snapping when dragging nodes, it is very hard to align multiple nodes together.

To counter this, we should update the arrow keys controls to snap to a grid. When a node is selected and the arrows keys are used to move it, the movements should snap to a 16x16 grid.

This will allow for a user to drag a node wherever they want and align it to a grid with arrows keys if needed.

**Comment by JakeMakesStuff** [comment]
This has been fixed in recent commits. 👍
