### ISSUE TITLE
[Security] Workflow gh-pages-workflow.yml is using vulnerable action JamesIves/github-pages-deploy-action

### ISSUE THREAD

**Issue by Freakston** [do-community/diagram-tool#51]
The workflow gh-pages-workflow.yml is referencing action JamesIves/github-pages-deploy-action using references 2.0.0. However this reference is missing the commit [661e33871bce8107c9af083f7415176608dce40e](https://github.com/JamesIves/github-pages-deploy-action/commits/661e33871bce8107c9af083f7415176608dce40e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by MattIPv4** [comment]
The commit you are referencing is on a different major version to what we are using at present.

Equally, the commit you are referring appears to be for a low-severity pollution issue in lodash. Given we're using this action in a controlled fashion to deploy some static assets, prototype pollution as a result of user-provided input in the action source is unlikely to be causing us any issues.

Feel free to open a PR to update the workflow in which we're using the action to be compatible with the new major version if you wish, but for now I'm going to close this issue.
