### ISSUE TITLE
Selection doesn't work

### ISSUE THREAD

**Issue by JakeMakesStuff** [do-community/diagram-tool#9]
### Description 

Selection does not work if you try and drag. I believe this is relating to the Z positioning.

### Steps to reproduce

Try dragging around items.

### Expected behavior

The nodes get selected.

### Screenshots

N/A

**Comment by MattIPv4** [comment]
Couple of other things relating to selection that seem wrong currently:

 - You cannot select a node to delete it. When you hover, it shows dots around the node, I think it would be a good visual indicator to show those always when the node is selected?
 - When a node is selected, the remove from categories option should show without needing to move the node around
